Repository PSDaily/Algorithm-Study, pull requests merged in 2025-05, with the labels that each got.

#74 [0430] 5972번 - 택배 배송
  C++/Graph/5972.cpp
  Java/src/main/java/graph/PS_5972.java
Labels: 다익스트라, 그래프이론, 최단거리

#78 [0502] 1926번 - 그림
  src/Problem1926.java
Labels: BFS

#76 [0430] 20006번 - 랭킹전 대기열
  python/랭킹전_대기열.py
Labels: 구현, 시뮬레이션

#77 [0501] 16988번 - Baaaaaaaaaduk2 (Easy)
  C++/Graph/16988.cpp
Labels: 브루트포스, BFS, DFS, 그래프탐색, 그래프이론

#79 [0502] 2178번 - 미로 탐색
  src/Problem2178.java
Labels: BFS, 그래프탐색, 그래프이론

#80 [0504] 7576번 - 토마토
  src/Problem7576.java
Labels: BFS, 그래프탐색, 그래프이론

#81 [0505] 2607번 - 비슷한 단어
  C++/구현/1244.cpp
  C++/구현/2607.cpp
  Java/src/main/java/string/PS_2607.java
Labels: 문자열, 구현

#82 [0506] 2169번 - 로봇 조종하기
  C++/DP/2169.cpp
Labels: 다이나믹 프로그래밍

#85 [0510] 28339번 - 이상한 드래프트
  C++/SlidingWindow/28339.cpp
Labels: 자료구조, 우선순위큐, 슬라이딩 윈도우, 트리를 사용한 집합과 맵

#86 [0514] 프로그래머스(고득점 Kit : 해시) - 베스트 앨범
  C++/Hash/베스트앨범.cpp
Labels: 해시

#87 [0515] 프로그래머스(고득점 Kit: 스택/큐, 완전탐색) 프로세스, 피로도
  C++/BruteForce/피로도.cpp
  C++/Queue/2075.cpp
  C++/Queue/프로세스.cpp
Labels: 브루트포스, 우선순위큐, 스택

#88 [0516] 프로그래머스(고득점 Kit : 정렬) H-Index
  C++/구현/H-Index.cpp
Labels: 정렬

#89 [0517] 프로그래머스(고득점 Kit: 해시, 큐) 완주하지 못한 선수, 다리를 지나는 트럭
  C++/Hash/완주하지못한선수.cpp
  C++/Queue/다리를지나는트럭.cpp
Labels: 해시, 큐
